apiVersion: apps/v1
kind: Deployment

metadata:
  name: blue-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: webapp
      version: blue

  template:
    metadata:
      labels:
        app: webapp
        version: blue

    spec:
      containers:
        - name: web-app
          image: europe-west2-docker.pkg.dev/tokyo-analyst-480722-h5/week3-images/blue:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80